### ISSUE TITLE
¿Qué es un Lote?

### ISSUE THREAD

**Issue by manuelvico0102** [Morad02/F1Data#10]
Para resolver #5 necesitamos saber qué es un lote. Un lote cuenta con los siguientes parámetros:

Peso de la materia 
Volumen de la materia

**Comment by JJ** [comment]
¿Estás hablando de una materia prima o de un lote específico de una materia prima? Es decir, si un pedido tiene materias primas, ¿siempre que haya la misma materia prima va a tener el mismo peso o volumen?
Ten en cuenta que esto es más un comentario sobre los nombres que otra cosa, pero los nombres pueden hacer que algo se entienda o no.
