### ISSUE TITLE
¿Qué es un pedido?

### ISSUE THREAD

**Issue by manuelvico0102** [Morad02/F1Data#11]
Para resolver #5 necesitamos saber qué es un pedido. Un pedido tiene la siguiente información:

Lista de las materias primas que conforman el pedido
Peso total del pedido
Volumen total del pedido

**Comment by JJ** [comment]
¿Alguna información más? ¿Un pedido va entero a un vehículo? Por lo que has hecho en la definición de `Pedido` y de `GestorVehículos` es así. ¿Qué información se usará de un pedido para asignarlo a uno o varios vehículos?

**Comment by manuelvico0102** [comment]
Pero eso no sería parte de la lógica de negocio? Yo es que había pensado que pedido tuviese métodos para calcular el peso y el volumen total del pedido, y ya esos datos se usarían para saber si es necesario asignarlo a uno o varios

**Comment by JJ** [comment]
¿Métodos o variables de instancia? Sea como fuere, ¿no sería parte del modelo?
