### ISSUE TITLE
¿Qué es un vehículo?

### ISSUE THREAD

**Issue by manuelvico0102** [Morad02/F1Data#12]
Para resolver #5 necesitamos saber qué es un vehículo. Un vehículo contiene los siguientes parámetros:

Consumo de combustible
Peso máximo que puede llevar el vehículo
Volumen máximo que puede llevar el vehículo

**Comment by JJ** [comment]
¿Te parece que "solución xx" aporte alguna información sobre qué decisión se ha tomado y por qué? ¿Y más cuando es *el único* texto que hay en *todos* los commits?
