### ISSUE TITLE
Entidad para vehiculos

### ISSUE THREAD

**Issue by manuelvico0102** [Morad02/F1Data#13]
Para resolver el problema propuesto en #5, tendremos que gestionar que un vehículo este disponible o este ya asignado.

**Comment by JJ** [comment]
No "tiene", sino "sabemos"

**Comment by JJ** [comment]
Una vez más, si dices "ha de gestionar" ya estás forzando una solución. Aquí deberías plantear qué sabemos sobre los vehículos, qué sucede con ellos, y quién los manejaría.

**Comment by JJ** [comment]
Has hecho 5 commits en este issue, los 5 dicen exactamente lo mismo. Repiten dos veces el número del issue, y no dicen absolutamente nada (en la primera línea) sobre en qué consiste esa solución. Eso te obliga a pinchar en cada uno de ellos para entender qué hace. ¿Crees que habría alguna forma mejor de formatear estos mensajes de commit?
