### ISSUE TITLE
¿Qué es una asignación mínima de vehículos?

### ISSUE THREAD

**Issue by Morad02** [Morad02/F1Data#24]
Para pasar #23 y  resolver #5 se necesita implementar la lógica de negocio que se encarga de asignar pedidos a vehículos minimizando el número de vehículos usados.  Una asignación está usando el mínimo número de vehículos, cuando no es posible reducir el número de vehículos asignados teniendo en cuenta el peso y volumen tanto de los lotes como de los vehículos.

**Comment by JJ** [comment]
Igual que en el objetivo 2 no se puede crear un issue que sea "problema X", no se puede crear un issue aquí que sea "implementación y". Tendrás que explicar qué factores se van a usar para minimizar el número de vehículos, y como sabes que el número de vehículos es mínimo.
