### ISSUE TITLE
Lenguaje de programación

### ISSUE THREAD

**Issue by manuelvico0102** [Morad02/F1Data#7]
Hay que elegir un lenguaje de programación para hacer tu proyecto. ¿Qué lenguaje tienes pensado utilizar?

**Comment by Morad02** [comment]
Tengo pensado usar Typescript aunque podría considerar Go .

**Comment by manuelvico0102** [comment]
Pues si te parece bien, podemos elegir TypeScript

**Comment by Morad02** [comment]
Perfecto, entonces typescript
